version: "3"

services:
    psql_db:
        image: postgres:13.3
        restart: "unless-stopped"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./volumes/psql_db/:/var/lib/postgresql/data
    was:
        build: .
        image: "jaljayeon_backend_was:${COMMIT}"
        restart: "unless-stopped"
        environment:
            - POSTGRES_HOST=psql_db
            - DEBUG=false
        depends_on:
            - psql_db
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ./volumes/staticfiles/:/usr/src/app/jaljayeon_backend/staticfiles
    ws:
        build: ./nginx
        image: "jaljayeon_backend_ws:${COMMIT}"
        restart: "unless-stopped"
        depends_on:
            - psql_db
            - was
        ports:
            - "80:80"
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ./volumes/staticfiles/:/home/app/jaljayeon_backend/staticfiles
